"""添加会话表与修改uid为user_id

Revision ID: 69a29eb83c1a
Revises: 
Create Date: 2026-01-07 15:43:37.311678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '69a29eb83c1a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_thread',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('thread_id', sa.String(length=255, collation='utf8mb4_bin'), nullable=True),
    sa.Column('title', sa.String(length=255, collation='utf8mb4_bin'), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_thread_user_id'), 'user_thread', ['user_id'], unique=True)
    op.add_column('chat_history', sa.Column('user_id', sa.String(length=255, collation='utf8mb4_bin'), nullable=True))
    op.drop_column('chat_history', 'uid')
    op.add_column('preset_question', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('preset_question', 'create_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preset_question', sa.Column('create_at', mysql.DATETIME(), nullable=True))
    op.drop_column('preset_question', 'created_at')
    op.add_column('chat_history', sa.Column('uid', mysql.VARCHAR(collation='utf8mb4_bin', length=255), nullable=True))
    op.drop_column('chat_history', 'user_id')
    op.drop_index(op.f('ix_user_thread_user_id'), table_name='user_thread')
    op.drop_table('user_thread')
    # ### end Alembic commands ###
